# Generated by Django 4.0.6 on 2022-08-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='categoria',
            field=models.CharField(choices=[('A', 'Alimentação'), ('S', 'Saúde'), ('M', 'Moradia'), ('T', 'Transporte'), ('E', 'Educação'), ('L', 'Lazer'), ('I', 'Imprevistos'), ('O', 'Outras')], default='O', max_length=3),
        ),
    ]
